apiVersion: v1
kind: Service
metadata:
  name: {{ include "hayhooks.fullname" . }}
spec:
  selector:
    {{- include "hayhooks.selectorLabels" . | nindent 4 }}
  ports:
  # Default port used by the Hayhooks Docker image
  - port: {{ .Values.service.port }}